### ISSUE TITLE
submit your frontend project

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/Frontend-Projects#11]
hey, you are welcome to submit your all frontend projects here to help everyone.
> add your copyright in footer

**Comment by Anurag-Singh-04** [comment]
Hey @devvsakib how can I contribute in this ?

**Comment by charandevreddy** [comment]
hey @devvsakib  can you assign me this?

**Comment by devvsakib** [comment]
> Hey @devvsakib how can I contribute in this ?

sure,

**Comment by devvsakib** [comment]
> hey @devvsakib can you assign me this?

assigned

**Comment by yf151290** [comment]
Can I add the frontend project

**Comment by devvsakib** [comment]
> Can I add the frontend project

assigned

**Comment by Sidkul2000** [comment]
Can I add the frontend project?

**Comment by devvsakib** [comment]
> Can I add the frontend project?

sure, assigned

**Comment by Anurag-Singh-04** [comment]
Hey @devvsakib we can add any frontend project in this ?

**Comment by devvsakib** [comment]
> Hey @devvsakib we can add any frontend project in this ?

yes

**Comment by Vishesh-Vijay** [comment]
please assign me this project

**Comment by adityabisoyi** [comment]
Hey @devvsakib, can you assign me this?

**Comment by devvsakib** [comment]
> Hey @devvsakib, can you assign me this?

done

**Comment by devvsakib** [comment]
> please assign me this project 
> 

done

**Comment by Vishesh-Vijay** [comment]
@devvsakib hey I've submitted my project can you mark for hacktober 2022 
Thank you

**Comment by devvsakib** [comment]
> @devvsakib hey I've submitted my project can you mark for hacktober 2022 Thank you

please check my review and make change, I will label your pr as hacktoberfest

**Comment by Vishesh-Vijay** [comment]
> > @devvsakib hey I've submitted my project can you mark for hacktober 2022 Thank you
> 
> please check my review and make change, I will label your pr as hacktoberfest

sir I've made the changes kindly check if it can be merged

**Comment by Anurag-Singh-04** [comment]
Hey @devvsakib I have submitted my project and created a PR. Can you please accept my PR with Hacktoberfest label. #21

**Comment by devvsakib** [comment]
> Hey @devvsakib I have submitted my project and created a PR. Can you please accept my PR with Hacktoberfest label. #21

done

**Comment by TanCodes** [comment]
assign me I want to contribute ;)

**Comment by ijaz-ali-dev** [comment]
Hey, I am interested to contribute to your repo by adding a requirement to it, can you please assign it to me?

**Comment by devvsakib** [comment]
> Hey, I am interested to contribute to your repo by adding a requirement to it, can you please assign it to me?

done

**Comment by devvsakib** [comment]
> assign me I want to contribute ;)

done

**Comment by Vishesh-Vijay** [comment]
@devvsakib sir you'd merged my project yesterday still it's not showing waiting in my hacktober fest page is there any specific reason for it?

**Comment by devvsakib** [comment]
> @devvsakib sir you'd merged my project yesterday still it's not showing waiting in my hacktober fest page is there any specific reason for it?

pr no?

**Comment by pjyoti121** [comment]
Please assign me this task

**Comment by devvsakib** [comment]
> Please assign me this task

assigned

**Comment by devvsakib** [comment]
@ijaz-ali-dev  @Sidkul2000  @TanCodes  @pjyoti121  @Vishesh-Vijay  @Anurag-Singh-04  @adityabisoyi @charandevreddy @RachitGarg-12 @yf151290 
You guys are always welcome to the family 
Discord - [join](https://discord.gg/xwRbDwnbMr)

**Comment by devvsakib** [comment]
if you are a reactjs developer, please join with us: https://github.com/devvsakib/hacktoberfest-react-project/

**Comment by ijaz-ali-dev** [comment]
Hi dear, i added my frontend project. 
thank you

**Comment by ijaz-ali-dev** [comment]
Hey, I am interested to contribute to one another your repo by adding a requirement to it, can you please assign it to me?

**Comment by devvsakib** [comment]
> Hey, I am interested to contribute to one another your repo by adding a requirement to it, can you please assign it to me?

sure

**Comment by HuzaifaChaudary** [comment]
Pls assign me this I am interested.

**Comment by devvsakib** [comment]
> Pls assign me this I am interested.

assigned
