### ISSUE TITLE
add Frontend Projects

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/Frontend-Projects#5]
### add frontend projects
language:
HTML
CSS
JAVASCRIPT

framework you can use:
Any JS framework - React, Angular, Vue etc
Any CSS framework - SASS, BOOTSTRAP, TAILWIND etc

**NOTE**: Unlimited assign possible, and you can add as much as project you want. Please keep in mind that, project will be use to help frontend developer.

**_Add your name as copyright in index file_**

**Comment by RachitGarg-12** [comment]
@devvsakib  i would like to contribute on this issue.

**Comment by devvsakib** [comment]
> @devvsakib i would like to contribute on this issue.

please go on, assigned

**Comment by udit9876gupta** [comment]
i want to add a front end project. Please assign this to me.

**Comment by pratyushkr11** [comment]
Hello @devvsakib sir, I want to add a front end project. Please assign me this issue.

**Comment by devvsakib** [comment]
> Hello @devvsakib sir, I want to add a front end project. Please assign me this issue.

assigned

**Comment by joe-sida** [comment]
Hello, I would like to add a project here, please.

**Comment by devvsakib** [comment]
> Hello, I would like to add a project here, please.

hey, assigned. add as much project you want and dont forget to put name in file as comment✅

**Comment by devvsakib** [comment]
> i want to add a front end project. Please assign this to me.

assigned

**Comment by yf151290** [comment]
I want to add portfolio project , can you assign

**Comment by charandevreddy** [comment]
assign me?

**Comment by devvsakib** [comment]
> assign me?

assigned

**Comment by devvsakib** [comment]
> I want to add portfolio project , can you assign

assigned

**Comment by Anurag-Singh-04** [comment]
Hey @devvsakib can you please assign this to me?

**Comment by devvsakib** [comment]
> Hey @devvsakib can you please assign this to me?

assigned

**Comment by Anurag-Singh-04** [comment]
Hey @devvsakib I have made a PR #23 . Please accept it under the label hacktoberfest.

**Comment by devvsakib** [comment]
> Hey @devvsakib I have made a PR #23 . Please accept it under the label hacktoberfest.

already labeled

**Comment by pjyoti121** [comment]
Please assign me this task

**Comment by devvsakib** [comment]
> Please assign me this task

assigned

**Comment by ijaz-ali-dev** [comment]
Hi sir, 
I want to add a landing page, can you assign it?

**Comment by devvsakib** [comment]
> Hi sir, I want to add a landing page, can you assign it?

sure
