### ISSUE TITLE
add a index file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/Frontend-Projects#54]
add a index file and a title with "Frontend Projects"
make sure title in the middle and center

**Comment by pixobia** [comment]
assign me this..,if it is only adding the file,and placing the text in center

**Comment by devvsakib** [comment]
> assign me this..,if it is only adding the file,and placing the text in center

assigned

**Comment by pixobia** [comment]
can you please tell me the location where should be the file added

**Comment by devvsakib** [comment]
> can you please tell me the location where should be the file added

in main folder Frontend-Projects

**Comment by Divi03** [comment]
I also Worked on it !
![image](https://user-images.githubusercontent.com/92048020/198723373-074af8d4-058a-43f8-baf8-a636c936957d.png)

**Comment by devvsakib** [comment]
> I also Worked on it ! ![image](https://user-images.githubusercontent.com/92048020/198723373-074af8d4-058a-43f8-baf8-a636c936957d.png)

that's amazing!!!!! wow

**Comment by Divi03** [comment]
few projects which do not have index.html are not working
should I push it as it is or wait for pixobia

**Comment by devvsakib** [comment]
@Divi03 wait for pixobia

**Comment by pixobia** [comment]
> few projects which do not have index.html are not working should I push it as it is or wait for pixobia

sorry,i had forget,right now i am busy i cant,please assign someone...

**Comment by Divi03** [comment]
@devvsakib I made a pull request for this issue , Please check !
